# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/Z_system/Z_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z_system || ORIG_REF_NAME==Z_system} -quiet] -quiet

# IP: bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z_system_processing_system7_0_0 || ORIG_REF_NAME==Z_system_processing_system7_0_0} -quiet] -quiet

# XDC: c:/xilinx/vivado/motorpwm/motorpwm.gen/sources_1/bd/Z_system/Z_system_ooc.xdc
